In [1]:
123

123

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.rcParams["font.family"] = 'Malgun Gothic'

plt.rcParams['axes.unicode_minus'] = False

In [3]:
df = pd.read_spss('data/Koweps_hpwc20_2025_beta1.sav')
df

,h20_id,h20_ind,h20_sn,h20_merkey,h_new,h_new1,h20_cobf,p20_wsc,p20_wsl,p20_wgc,...,wc20_63,wc20_64,wc20_5aq4,wc20_5aq5,wc20_5aq6,h20_pers_income1,h20_pers_income2,h20_pers_income3,h20_pers_income4,h20_pers_income5
0,2.0,1.0,1.0,20101.0,0.0,0.0,NaN,0.270248,0.269086,1513.433983,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
1,3.0,1.0,1.0,30101.0,0.0,0.0,NaN,0.424537,0.400322,2377.476553,...,NaN,NaN,NaN,NaN,NaN,NaN,2423.0,NaN,0.0,NaN
2,4.0,1.0,1.0,40101.0,0.0,0.0,NaN,0.230720,0.216585,1292.070254,...,NaN,NaN,NaN,NaN,NaN,NaN,337.0,NaN,0.0,NaN
3,6.0,1.0,1.0,60101.0,0.0,0.0,NaN,0.541744,0.498132,3033.853323,...,1.0,3.0,2.0,2.0,3.0,2825.0,NaN,NaN,0.0,NaN
4,6.0,1.0,1.0,60101.0,0.0,0.0,NaN,0.852575,0.827786,4774.555169,...,1.0,5.0,1.0,5.0,4.0,NaN,2278.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14910,12010.0,17.0,1.0,120101701.0,0.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,12820.0,NaN,NaN,0.0,NaN
14911,12010.0,17.0,1.0,120101701.0,0.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3149.0,NaN,0.0,NaN
14912,12010.0,17.0,1.0,120101701.0,0.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
14913,12011.0,17.0,1.0,120111701.0,0.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6600.0,NaN,0.0,NaN
14914,12011.0,17.0,1.0,120111701.0,0.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,NaN

In [4]:
raw_data = df.copy()

In [5]:
df.columns

Index(['h20_id', 'h20_ind', 'h20_sn', 'h20_merkey', 'h_new', 'h_new1',
       'h20_cobf', 'p20_wsc', 'p20_wsl', 'p20_wgc',
       ...
       'wc20_63', 'wc20_64', 'wc20_5aq4', 'wc20_5aq5', 'wc20_5aq6',
       'h20_pers_income1', 'h20_pers_income2', 'h20_pers_income3',
       'h20_pers_income4', 'h20_pers_income5'],
      dtype='str', length=834)

In [6]:
df.describe()

,h20_id,h20_ind,h20_sn,h20_merkey,h_new,h_new1,h20_cobf,p20_wsc,p20_wsl,p20_wgc,...,wc20_63,wc20_64,wc20_5aq4,wc20_5aq5,wc20_5aq6,h20_pers_income1,h20_pers_income2,h20_pers_income3,h20_pers_income4,h20_pers_income5
count,14915.000000,14915.000000,14915.000000,1.491500e+04,14915.000000,14915.000000,107.000000,9241.000000,9241.000000,9241.000000,...,2661.000000,2661.000000,2661.000000,2661.000000,2661.000000,2772.000000,4014.000000,1041.000000,14915.000000,844.000000
mean,6096.268119,7.153000,1.005967,6.096340e+07,0.154140,0.226282,2.383178,1.000000,1.000000,5600.158532,...,2.987223,3.545284,3.286359,4.465990,3.194288,5118.640332,1722.461136,4024.195005,5.903587,1369.016588
std,3623.784870,6.832234,0.145669,3.623832e+07,0.361095,0.418438,1.740987,0.671986,0.758854,3763.230719,...,2.094709,2.300522,1.069009,0.782365,1.210007,3034.664301,1685.512368,5655.692252,85.639864,2685.001871
min,2.000000,1.000000,1.000000,2.010100e+04,0.000000,0.000000,1.000000,0.008632,0.000000,48.343287,...,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,29.000000,-7510.000000,0.000000,-5592.000000
25%,2969.000000,1.000000,1.000000,2.969010e+07,0.000000,0.000000,1.000000,0.476963,0.436834,2671.068146,...,1.000000,2.000000,3.000000,4.000000,2.000000,3168.000000,348.000000,1200.000000,0.000000,202.000000
50%,5663.000000,5.000000,1.000000,5.663010e+07,0.000000,0.000000,2.000000,0.921132,0.853645,5158.487776,...,2.000000,3.000000,3.000000,5.000000,3.000000,4334.500000,1200.000000,3000.000000,0.000000,502.500000
75%,9535.000000,17.000000,1.000000,9.535070e+07,0.000000,0.000000,2.000000,1.388024,1.372734,7773.152732,...,5.000000,5.000000,4.000000,5.000000,4.000000,6502.000000,2592.000000,5210.000000,0.000000,1552.000000
max,12011.000000,20.000000,9.000000,1.201117e+08,1.000000,1.000000,7.000000,4.181975,4.442006,23419.724142,...,9.000000,9.000000,6.000000,6.000000,6.000000,27300.000000,20400.000000,110750.000000,5400.000000,40000.000000

h20_g3 성별  
h20_g4 출생연도  
h20_eco9 직종  
p2002_8aq1 월평균 임금

In [7]:
df[['h20_g3',
'h20_g4',
'h20_eco9',
'p2002_8aq1']]

       h20_g3  h20_g4  h20_eco9  p2002_8aq1
0         2.0  1945.0       NaN         NaN
1         1.0  1948.0     942.0       200.0
2         1.0  1942.0       NaN         NaN
3         1.0  1962.0     855.0       235.0
4         2.0  1963.0     314.0       190.0
...       ...     ...       ...         ...
14910     1.0  1975.0     222.0      1010.0
14911     2.0  1976.0     313.0       260.0
14912     2.0  2009.0       NaN         NaN
14913     1.0  1964.0     151.0       550.0
14914     2.0  1964.0       NaN         NaN

[14915 rows x 4 columns]